### ISSUE TITLE
the visualization demo code for clustering doesn't work

### ISSUE THREAD

**Issue by mahabenfares** [hoanganhngo610/river-clustering-demo-2022#1]
Hello, I tested your demo notebook code (this one: Visualization demo using Holoviews (for clustering problem).ipynb) and i got the same error that you got when calling the function run_experiment(). Did you solve the problem? or do you have any idea how to solve it please? i hope you can see my message. Thanks.

**Comment by hoanganhngo610** [comment]
Thank you so much @mahabenfares for reaching out! I believe that the error when function `run_experiment()` has been fixed in my last run locally. Let me try to replicate the error (or see if the latest changes has been made available online) and get back to you ASAP!

**Comment by mahabenfares** [comment]
thank you so much for your quick return. I'll wait for your response.

**Comment by hoanganhngo610** [comment]
Dear @mahabenfares. I have just updated the notebooks accordingly, as per the latest changes on the River GitHub repository. Please make sure that you have the latest version of River (even in development) installed using
```
pip install git+https://github.com/online-ml/river --upgrade
```
and the dependencies all available.

If the problem still persists for you, please do not hesitate to contact me again!

**Comment by mahabenfares** [comment]
Thank you it worked! I have one more question if you can help please, After executing run_experiments function, how can I visualize real-time results (changes of metrics values in the plot)? It's my first time that I use holoviews. Do i just have to display the variable layout_tab after the function has finished executing?

**Comment by hoanganhngo610** [comment]
@mahabenfares As you may know, there are two platforms that you can run your Python notebooks on, Jupyter Notebook and JupyterLabs. Unfortunately, the requirements for HoloViews to work on these two platforms are different. My advise would be to go for Jupyter Notebook for the sake of simplicity.

- If you run your notebook on Jupyter Notebook, after running `run_experiments()`, you do not really actually need to do anything. The cell that has `layout_tabs` already called (the cell right before the definition of `run_experiments` will automatically update by time and will stop when they have iterated through all observations in the dataset. Also, please note that this task is quite CPU-heavy, so make sure that you try to maximize the space on your system for this to run. With my configuration (Macbook Pro 14inch 2021), the results appear instantaneously.
- If you run your notebook on JupyterLabs, please follow the guide from their official website [here](https://holoviews.org/user_guide/Installing_and_Configuring.html). Basically, you have to install a extension for it to work.

Hope this will help!

**Comment by hoanganhngo610** [comment]
@mahabenfares Please let me know if the problem has been solved for you. Else, I would proceed to close this issue.

In any case, you can always contact me via email at <hoang.ngo@telecom-paris.fr>.

**Comment by mahabenfares** [comment]
Hello, yeah it worked! sorry for the late response.
